baseURL = "/"
languageCode = "fr-fr"
paginate = 6
summarylength = 10
title = "Harmoni Culture Gabon | l'actualités de la transition"
themes = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Acceuil"
    url= ""
    weight= 1
  [[menu.main]]
    name = "À Propos"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/Gabon.svg"
  author = "HCG"
  authorThumb = "images/author.png"
  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  authorPhone = "+33-257634 534"
  instaUsername = "mary_astor"
  facebookUsername = "mary_astor"
  twitterUsername = "mary_astor"
  linkedinUsername = "mary_astor"
  blogTitle = "Informations sur HCG"
  blogSubTitle = "Voir les dernières actualités sur Harmoni Culture Gabon"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
